### ISSUE TITLE
Refactoring Quiz Game.

### ISSUE THREAD

**Issue by ductran999** [DucTran999/small-project#25]
- Add specification documents and docstrings for code.

**Comment by danielngo99** [comment]
Yesterday, I ran the program before writing the document. The program runs ok but I found some inconveniences. When I want to add a new topic or question, I have to enter it directly into the file (text file and JSON file) instead of through the program. I'm having a little trouble writing JSON, and I think it's also annoying for those new to JSON. So new features to manage topics are indeed necessary. What do you think?

**Comment by ductran999** [comment]
I see your point. Adding these new features will make the program even more exciting and extensible. But it also makes the code more complex. To manage it, do you have any suggestions?

**Comment by danielngo99** [comment]
Based on the operation of the program, I want to implement the MVC architecture pattern.

**Comment by danielngo99** [comment]
Based on the program's operation, I want to implement the MVC architecture pattern.

**Comment by ductran999** [comment]
Ok. I will create a new milestone for developing quiz game.
